language: node_js
node_js:
    - "8.9.4"
script:
    - "npm install -g pxt"
    - "pxt target minecraft"
    - "pxt install"
    - "pxt build --cloud"
sudo: false
cache:
    directories:
    - npm_modules
    - pxt_modules